import { type Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Topbar from "@/components/Topbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TaskHive",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className="flex h-screen w-full">
            {/* Sidebar: always on left */}
            <Sidebar />

            {/* Main Section: Topbar + page content */}
            <div className="flex-1 flex flex-col">
              {/* 🔥 Topbar goes here */}
              <Topbar />

              {/* Page content */}
              <main className="flex-1 overflow-auto p-4">{children}</main>
            </div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
